# Generated by Django 2.0.4 on 2018-05-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SheetApp', '0003_auto_20180509_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyers',
        ),
    ]
